# Site settings
author: David Burton
title: Math Teacher to Data Guru
header-img: img/home-bg.png
email: davidgburton@yahoo.com
copyright_name: David Burton
description: > # this means to ignore newlines until "baseurl:"
  A math teacher's journey into data science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: notacyborg4long
github_username:  Burton-David

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
